# ruff: noqa: E501
"""Run-centric browser projection for the on-premises Agent API."""

AGENT_RUN_UI = r"""<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>Trace Marketing Agent</title>
<style>
:root{font:15px/1.6 system-ui,sans-serif;color:#18181b;background:#f4f4f5}body{margin:0}header,main{max-width:1180px;margin:auto;padding:20px}header{display:flex;gap:12px;align-items:center}h1{font-size:22px;margin-right:auto}.card{background:white;border:1px solid #ddd;border-radius:14px;padding:18px;margin-bottom:16px}input,textarea,button{font:inherit}input,textarea{box-sizing:border-box;width:100%;padding:9px;border:1px solid #bbb;border-radius:8px}textarea{min-height:100px}button,.button{padding:9px 13px;border:0;border-radius:8px;background:#18181b;color:white;cursor:pointer;text-decoration:none}button:disabled{opacity:.5;cursor:wait}.grid{display:grid;grid-template-columns:320px minmax(0,1fr);gap:16px}.fields{display:grid;gap:10px}.muted{color:#71717a}.run{display:block;width:100%;text-align:left;padding:10px;margin-bottom:8px;background:#f4f4f5;color:#18181b}.records{max-height:420px;overflow:auto}.asset-preview{max-width:100%;max-height:640px;object-fit:contain}.asset-meta{overflow-wrap:anywhere}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f4f4f5;padding:10px;border-radius:8px}.actions{display:flex;gap:8px;flex-wrap:wrap}[hidden]{display:none!important}#message{min-height:1.6em;overflow-wrap:anywhere}@media(max-width:760px){.grid{grid-template-columns:1fr}header{flex-wrap:wrap}}
</style></head><body>
<header><h1>Trace Marketing Agent</h1><a class="button" id="login" href="/auth/login" hidden>회사 계정으로 로그인</a><button id="logout" hidden>로그아웃</button></header>
<main><section class="card fields"><div id="identity" class="muted"></div><label id="tokenField">로컬 서비스 토큰 <input id="token" type="password" autocomplete="off"></label>
<label>마케팅 목표 <textarea id="goal" placeholder="일본의 생산성 앱 마케팅 사례를 조사하고 다음에 시도할 콘텐츠를 제안해줘"></textarea></label>
<label>성공 기준 <input id="criteria" value="출처와 불확실성을 포함해 실행할 다음 행동을 제안한다"></label>
<div class="actions"><button id="create">조사 시작</button><button id="refresh">새로고침</button></div><div id="message" role="status" aria-live="polite"></div></section>
<div class="grid"><section class="card"><h2>실행 목록</h2><div id="runs"></div></section><section class="card"><h2>실행 내용</h2><div id="detail" class="muted">실행을 선택하세요.</div></section></div>
</main><script>
const $=id=>document.getElementById(id);const pathRun=location.pathname.match(/^\/runs\/([^/]+)$/);let selected=pathRun?decodeURIComponent(pathRun[1]):null,csrf='',browserMode=false,pendingDigest=null,selectedRevision=null,busy=false,retryJob=null,sessionOwner='local',loadVersion=0,assetPreviewVersion=0;
const states={created:'접수',running:'조사 중',awaiting_input:'추가 근거 필요',awaiting_tool:'도구 결과 대기',awaiting_approval:'승인 필요',completed:'완료',stopped:'종료',blocked:'확인 필요',failed:'실패',awaiting_reconciliation:'실행 결과 확인 필요'};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(path,options={}){const headers={'content-type':'application/json'};if(browserMode){if(csrf)headers['x-trace-csrf']=csrf}else{if(!$('token').value)throw Error('로컬 서비스 토큰을 입력하세요.');headers.authorization=`Bearer ${$('token').value}`}
 const response=await fetch(path,{...options,headers,credentials:'same-origin'});const body=await response.json();if(!response.ok){if(response.status===401)throw Error('로그인이 필요하거나 만료됐습니다. 다시 로그인하세요.');const e=Error(body.error||`HTTP ${response.status}`);e.status=response.status;throw e}return body}
async function list(){const body=await api('/v1/runs');$('runs').innerHTML=body.runs.map(r=>`<button class="run" data-id="${esc(r.run_id)}"><b>${esc(r.goal.objective.slice(0,150))}</b><br>${esc(states[r.state]||r.state)}</button>`).join('')||'<span class="muted">아직 실행이 없습니다.</span>';document.querySelectorAll('.run').forEach(el=>el.onclick=()=>load(el.dataset.id).catch(showError))}
async function load(id){selected=id;const version=++loadVersion;const body=await api(`/v1/runs/${encodeURIComponent(id)}`);if(selected!==id||version!==loadVersion)return;const r=body.run;pendingDigest=body.pending_invocation_sha256;selectedRevision=r.revision;const reasoning=[...body.records].reverse().find(x=>x.kind==='reasoning');const summary=reasoning?.payload?.decision?.reasoning_summary||'';
 const invocation=[...body.records].reverse().find(x=>x.kind==='invocation');const approval=r.state==='awaiting_approval'?`<h3>실행 승인</h3><p>아래 내용으로 외부 도구를 실행합니다.</p><pre>${esc(JSON.stringify(invocation?.payload?.input,null,2))}</pre><div class="actions"><button id="approve">이 내용 승인</button><button id="reject">거절</button></div>`:'';
 const input=r.state==='awaiting_input'?'<label>추가 근거 또는 답변<textarea id="evidence"></textarea></label><button id="submitInput">이어서 실행</button>':'';
 $('detail').innerHTML=`<h3>${esc(r.goal.objective)}</h3><p><b>${esc(states[r.state]||r.state)}</b></p><pre>${esc(summary)}</pre>${approval}${input}<button id="resume">중단된 조사 이어서 확인</button><section aria-labelledby="assets-title"><h3 id="assets-title">작업 이미지</h3><div id="assets">이미지 목록을 불러오는 중입니다.</div><div id="assetPreview"></div></section><section aria-labelledby="performance-title"><h3 id="performance-title">성과 · 사람 보고</h3><p class="muted">외부 검증 수치가 아닙니다. 미보고 값은 0으로 계산하지 않습니다.</p><div id="performance" aria-live="polite">기록을 불러오는 중입니다.</div></section><details><summary>실행 기록 · Run journey</summary><div class="records">${body.records.map(x=>`<details><summary>${esc(x.kind)}</summary><pre>${esc(JSON.stringify(x.payload,null,2))}</pre></details>`).join('')}</div></details>`;
 if($('approve'))$('approve').onclick=()=>approvalJob('granted');if($('reject'))$('reject').onclick=()=>approvalJob('rejected');if($('submitInput'))$('submitInput').onclick=()=>submit({action:'input',run_id:selected,expected_revision:selectedRevision,evidence:{note:$('evidence').value}});$('resume').onclick=()=>submit({action:'resume',run_id:selected});void loadPerformance(id,version);void loadAssets(id,version);}
const assetKinds={native_trace_capture:'앱 캡처',edited_promotion:'가공 홍보 이미지',background_asset:'배경 자산',phone_mockup:'폰 목업'};
function assetOrigin(a){return a.origin==='human_reported'?'사람 보고':a.origin==='worker_receipt'?'도구 실행 기록':'출처 상태 미확인'}
function assetQA(qa){if(!Array.isArray(qa)||!qa.length)return '아직 기록 없음';const methods={deterministic:'정량 검사',model_visual:'모델 시각 검토',human_review:'사람 검수'},statuses={pending:'대기',passed:'통과',failed:'수정 필요'};return qa.slice(0,3).map(q=>`${esc(methods[q.method]||q.method)} ${esc(statuses[q.status]||q.status)} · ${esc(q.locale||'공통')}`).join(' / ')}
async function loadAssets(id,version){try{const result=await api(`/v1/runs/${encodeURIComponent(id)}/assets`);if(selected!==id||version!==loadVersion)return;const rows=result.assets.slice(0,6);$('assets').innerHTML=rows.map(a=>`<button class="asset-choice" data-asset="${esc(a.asset_id)}">${esc(assetOrigin(a))} · ${esc(assetKinds[a.kind]||a.kind)} · ${esc(a.locale||'언어 미지정')} · ${esc(a.asset_id)}</button>`).join(' ')||'<p class="muted">연결된 이미지가 없습니다.</p>';document.querySelectorAll('.asset-choice').forEach(button=>button.onclick=()=>previewAsset(id,version,button.dataset.asset))}catch(e){if(selected===id&&version===loadVersion)$('assets').textContent='이미지 목록을 불러오지 못했습니다.'}}
async function previewAsset(id,version,assetId){const preview=++assetPreviewVersion;$('assetPreview').textContent='이미지를 불러오는 중입니다.';try{const result=await api(`/v1/runs/${encodeURIComponent(id)}/assets/${encodeURIComponent(assetId)}`);if(selected!==id||version!==loadVersion||preview!==assetPreviewVersion)return;const a=result.asset,b64=result.image_base64;if(typeof b64!=='string'||b64.length>14000000||!/^[A-Za-z0-9+/]*={0,2}$/.test(b64))throw Error('invalid image');const mime=b64.startsWith('iVBORw0KGgo')?'image/png':b64.startsWith('/9j/')?'image/jpeg':null;if(!mime)throw Error('unsupported image');$('assetPreview').innerHTML=`<p class="asset-meta"><b>${esc(assetOrigin(a))} · ${esc(assetKinds[a.kind]||a.kind)} · ${esc(a.locale||'언어 미지정')}</b><br>버전 ${esc(a.revision)} · ${result.stale?'원본 변경으로 재검토 필요':'현재 원본 연결'}<br>출처: ${esc(a.source)}<br>검수 기록: ${assetQA(a.qa)}<br>이번 조회: 시각 검증 미수행 · 제품 기능 증거 미검증</p><img class="asset-preview" src="data:${mime};base64,${b64}" alt="${esc(a.asset_id)} 작업 결과"><p class="muted">가공 이미지는 앱 기능·언어·폰트 지원의 증거가 아닙니다. 표시 자체는 시각 검증을 뜻하지 않습니다.</p>`}catch(e){if(selected===id&&version===loadVersion&&preview===assetPreviewVersion)$('assetPreview').textContent='이미지를 불러오지 못했습니다. 목록에서 다시 선택하세요.'}}
async function loadPerformance(id,version){try{const result=await api(`/v1/runs/${encodeURIComponent(id)}/performance`);if(selected!==id||version!==loadVersion)return;const rows=result.observations.slice(0,6);const metric=(label,value)=>`${label} ${value===null||value===undefined?'미보고':esc(value)}`;$('performance').innerHTML=rows.map(r=>`<article><p><b>${esc(r.channel)} · ${esc(r.account_id)} · ${esc(r.country)}</b><br>${esc(r.publication_ref)}<br><span class="muted">관측 ${esc(r.window_start)} ~ ${esc(r.window_end)}</span><br>${[['조회',r.views],['좋아요',r.likes],['댓글',r.comments],['클릭',r.clicks],['설치',r.installs]].map(([label,value])=>metric(label,value)).join(' · ')}</p></article>`).join('')||'<p class="muted">이 업무에 기록된 성과가 없습니다.</p>';if(rows.length)$('performance').innerHTML+='<p class="muted">불러온 기록 중 최근 최대 6개를 표시합니다.</p>'}catch(e){if(selected===id&&version===loadVersion)$('performance').textContent='성과 기록을 불러오지 못했습니다. 실행 내용은 계속 확인할 수 있습니다.'}}
function showError(e){$('message').textContent=e.message}
async function watch(job){for(;;){const status=await api(`/v1/jobs/${encodeURIComponent(job.job_id)}`);if(status.state==='done'||status.state==='blocked'){sessionStorage.removeItem('trace.pendingJob');retryJob=null;await list();await load(status.run_id);$('message').textContent=status.state==='done'?'실행 상태를 갱신했습니다.':'실행이 중단됐습니다. 기록을 확인하고 조사를 이어서 확인하세요.';return} $('message').textContent='요청을 접수했습니다. 조사 중입니다. 이 화면을 닫아도 서버에서 계속 진행합니다.';await new Promise(r=>setTimeout(r,1500))}}
async function submit(fields){if(busy)return;busy=true;$('create').disabled=true;try{const stored=sessionStorage.getItem('trace.pendingJob');if(stored){const saved=JSON.parse(stored);if(saved.owner===sessionOwner){await watch(saved);return}sessionStorage.removeItem('trace.pendingJob')}const job=retryJob||{job_id:crypto.randomUUID(),...fields};retryJob=job;await api('/v1/jobs',{method:'POST',body:JSON.stringify(job)});sessionStorage.setItem('trace.pendingJob',JSON.stringify({job_id:job.job_id,run_id:job.run_id,owner:sessionOwner}));await watch(job)}catch(e){if(e.status>=400&&e.status<500&&e.status!==401){retryJob=null;sessionStorage.removeItem('trace.pendingJob')}showError(e)}finally{busy=false;$('create').disabled=false}}
function approvalJob(decision){submit({action:'approval',run_id:selected,decision,invocation_sha256:pendingDigest,expires_at:decision==='granted'?new Date(Date.now()+300000).toISOString():null})}
$('create').onclick=()=>submit({action:'create',run_id:`run-${crypto.randomUUID()}`,goal:{objective:$('goal').value,success_criteria:[$('criteria').value],context:{}},budget:{max_tool_calls:8,max_cost_units:50}});
$('refresh').onclick=async()=>{try{const pending=sessionStorage.getItem('trace.pendingJob');if(pending)await submit(JSON.parse(pending));else{await list();if(selected)await load(selected)}}catch(e){showError(e)}};
$('logout').onclick=async()=>{try{await api('/auth/logout',{method:'POST',body:'{}'});sessionStorage.removeItem('trace.pendingJob');location.reload()}catch(e){showError(e)}};
async function init(){try{const config=await fetch('/auth/config').then(r=>r.json());browserMode=config.browser_login;$('login').hidden=!browserMode;$('tokenField').hidden=browserMode;if(browserMode){const session=await api('/auth/session');csrf=session.csrf;sessionOwner=`${session.tenant_id}:${session.principal_id}`;$('identity').textContent=`${session.tenant_id} · ${session.principal_id}`;$('logout').hidden=false;$('login').hidden=true}if(browserMode||$('token').value){await list();if(selected)await load(selected);const pending=sessionStorage.getItem('trace.pendingJob');if(pending)await submit(JSON.parse(pending))}}catch(e){showError(e)}}init();
</script></body></html>"""

__all__ = ["AGENT_RUN_UI"]
